### ISSUE TITLE
check for pre conditions build_te

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-builder#11]
Before running build_te, check for pre conditions:
- maven has been installed
- github has been installed
- JDK has been install. - need to be able to run the jar command
- check that the tomcat install is the full one and that bin/catalina.sh exists (In Windows there is a version that is not the full Tomcat, we need the full Tomcat)

First windows
Then unix

**Comment by keshavnangare** [comment]
Updated with this commit 9653b958dc40b70ff6f9da8c8f621898dc8c20dd
