### ISSUE TITLE
build_te.sh shoud not check java and maven by "java" and "maven" from grep output

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine-builder#12]
As build_te.sh check installed java and maven by "java" and "maven" from grep output. It does not work as if:
+ I installed java OpenJDK (no "java" string from the output)
  java -version 2>&1 
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

+ Maven:
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/user/setup/Maven
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_25/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.28.2.el7.x86_64", arch: "amd64", family: "unix"

so this script should check by grep output with "version" is enough to make sure these binary files are existing.

**Comment by aaime** [comment]
I have had the same issue with OpenJDK

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigations.

**Comment by keshavnangare** [comment]
Fixed with this commit: 212ef334eb85d83ab7b7bf42a2d4ffd7396fe671

**Comment by dstenger** [comment]
@keshav-nangare Can you please create a pull request?

**Comment by keshavnangare** [comment]
Created the PR.
