### ISSUE TITLE
install-all-tests.sh requires at least 4 arguments (not 3 arguments as in README)

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine-builder#13]
I tried with install-all-tests.sh as in README, it will fail as it need a folder to clone and build test suites

`./install-all-tests.sh $TE_BASE $catalina_base/webapps/$war production-releases/201601.csv`

[FAIL] Argument 4 '' is not a directory.

Usage install-all-tests.sh TE_BASE TEAM_ENGINE CSV_FILE DIR_TO_BUILD

so the correct for example should be

`./install-all-tests.sh $TE_BASE $catalina_base/webapps/$war production-releases/201601.csv $tmp_folder_to_build_test_suite`

**Comment by ghobona** [comment]
Issue overtaken by events.
