### ISSUE TITLE
install-all-tests.sh will not update newest test suite on version 4.1.0 (example in README)

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine-builder#14]
When first I build teamengine with this command:
`./build_te.sh -a 4.1.0b -t /home/user/Tomcat_teamengine`
it will build version 4.1.0 and after run install-all-tests.sh correctly with input arguments (TE_BASE, CATALINA_BASE/webapp/team_engine, csv_file_ets, tmp_directory_to_build_testsuite)

and visit: localhost:8080/teamengine, it does not show the test suites from csv_file_ets (only 1 sample test suite for XML note). So README file should update with using the newest version of TeamEngine (as I built it again with: 

./build_te.sh -t /home/user/Tomcat_TeamEngine

and all test suites from install-all-tests.sh will be displayed in lcoalhost:8080/teamengine).

**Comment by ghobona** [comment]
Issue overtaken by events.
