### ISSUE TITLE
find-repeated-jars.sh is not reporting correctly the jars to be removed

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-builder#15]
It is not working properly when having these

geotk-metadata-3.21.jar 
geotk-metadata-sql-3.21.jar  
json-20080701.jar   
json-simple-1.1.1.jar   
teamengine-spi-4.10.jar
teamengine-spi-ctl-4.10.jar           

It reports the following
geotk-metadata-sql-3.21.jar json-simple-1.1.1.jar teamengine-spi-ctl-4.10.jar

Need to take the text string before the last of numbers (before -) and compare if the string is ok

**Comment by keshavnangare** [comment]
@bermud @dstenger 

Can you please provide the more jars or you can share lib directory? So I can test this script.

**Comment by dstenger** [comment]
Can you please describe the expected behaviour?

**Comment by keshavnangare** [comment]
Fixed with this commit: b2bba72

**Comment by dstenger** [comment]
@keshav-nangare Can you please create a pull request?

**Comment by keshavnangare** [comment]
Created the PR.
