### ISSUE TITLE
create script for windows

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-builder#4]
Provide all building scripts to build in a Windows machine to easily run TEAM Engine and incorporate selected versions of tests. These scripts and its dependenceis:
- build_te.sh
- install-all-tests.sh

**Comment by bermud** [comment]
Will try to use jars instead 7-zip

**Comment by keshavnangare** [comment]
We have used the inbuilt unzip utility to unzip the file in windows.
Fixed with this commit 2bf1dc616423e0c4d38c6f60b417f6e858703749
