### ISSUE TITLE
build_te.bat is not working

### ISSUE THREAD

**Issue by daltonch** [opengeospatial/teamengine-builder#9]
## D:\temp\teamengine-builder>build_te.bat  -a 4.1.0b -t D:\apps\tomcat\apache-tomcat-7.0.67

In TE tags case...."4.1.0b"
In tomcat_base case...."D:\apps\tomcat\apache-tomcat-7.0.67"
 "[INFO] The git url  was not provided,  so 'https://github.com/opengeospatial/teamengine.git' will be used"
"[INFO] Building " 4.1.0b
"[INFO] Base folder was not provided, so it will attempt to build in the user's directory 'C:\te-build'"
"[INFO] Using Base folder: C:\te-build"
"[INFO] War name was not provide, so 'teamengine' will be used"
"[INFO] The folder site was not provided, so folder_site will be used: " D:\temp\teamengine-builder\site
"[INFO] - cleaning - removing folder to build "C:\te-build
0 File(s) copied
File Not Found
^CTerminate batch job (Y/N)? y

D:\temp\teamengine-builder>

Hangs after File Not Found

**Comment by bermud** [comment]
There is a new version of the bat file
https://github.com/opengeospatial/teamengine-builder/blob/master/build_te.bat

I also suggest to test with TE 4.5.

@keshav-nangare, if you have further insight about the problem please let us know. Thank you.

**Comment by keshavnangare** [comment]
I have updated the script, just take latest pull and try, let me know if there is an issue.

**Comment by bermud** [comment]
It was tested in Windows 8.

**Comment by bermud** [comment]
@daltonch, we are going to close this issue. Let us know if you have further problems.

**Comment by daltonch** [comment]
Great thanks, haven't had to chance to test it out yet but thanks for looking into it for me!
